version: "3"

services:
  nginx:
    build: ./nginx
    ports:
    - '8080:80'
    depends_on:
    - authorization
    - resource
  authorization:
    build: ./authorization
    environment:
      PASSWORD: password
  resource:
    build: ./resource
